# Generated by Django 3.1.7 on 2021-03-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_cart_cartproduct_category_order_product_productview_review_slider_trendingproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
